import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import type { JSX } from 'react/jsx-runtime';
import { HeaderClient } from '../components/header-client';
import { getHeaderHtml } from '../lib/header.server';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): Promise<JSX.Element> {
  const headerHtml = await getHeaderHtml();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: prerendered header HTML is trusted */}
        <div id="header" dangerouslySetInnerHTML={{ __html: headerHtml }} />
        <HeaderClient />
        {children}
      </body>
    </html>
  );
}
